### ISSUE TITLE
Userstory: Freie Zeit vor und/oder nach Terminen

### ISSUE THREAD

**Issue by HansenBerlin** [HansenBerlin/altenheim-kalender#116]
Als User möchte ich bei der smarten Vorschlagsfunktion eine Option haben, vor und/oder nach den Terminen freie Zeit zu blocken, also einen Abstand zu definieren zu vorhandenen Terminen. Wenn ich also Dienstags zu definierten Öffnungszeiten in den nächsten vier Wochen freie Termine von einer Stunde Länge als Vorschläge haben will, möchte ich eine Margin von bspw. 20 Minuten festlegen (analog zu den Fahrtzeiten). Nun werden mir nur Termine vorgeschlagen, die minimal 20 Minuten nach Ende eines vorhandenen Termins beginnen und ich nach Ende des Vorschlags noch 20 Minuten Zeit bis zum nächsten Termin habe. Die Dauer des vorgeschlagenen Termins bleibt dabei bei 1 Std. (für dieses Beispiel).

Akzeptanzkriterien:
Ich habe eine zusätzliche Option, eine "margin" festzulegen.
Die Vorschläge berücksichtigen diese margin.
Ich habe die Möglichkeit, eine default-margin festzulegen.
- [x] #122 
- [x] #125
- [x] #99 
- [x] #94 
- [x] #126

**Comment by CorentinHamp** [comment]
Funktioniert in 0.4.28
