### ISSUE TITLE
Userstory: Statistiken zu Terminverteilung

### ISSUE THREAD

**Issue by HansenBerlin** [HansenBerlin/altenheim-kalender#117]
Als User möchte ich mit übersichtlichen Graphen über Terminhäufigkeiten einen Überblick bekommen. Anhand verschiedener Vorgaben wird mir z.B. angezeigt, an welchen Tagen die höchste Termindichte herrscht oder wie hoch prozentual der Anteil bestimmter Termine (z.B. mit TAG "Arbeit" oder "Uni") im Vergleich zu anderen ist. Ein möglicher Usecase für diese Funktion wäre die Überprüfung der Workloads für bestimmte Projekte oder arbeitsbezogene Termine.

Akzeptanzkriterien:
Über einen Menüpunkt kann ich mir eine Art Dashboard anzeigen lassen.
Hier kann ich nach definierten Kriterien eingrenzen (Termine mit TAG XY, Termine an Montagen, Termine mit einer Dauer von mehr als einer Stunde usw.) was mir angezeigt wird.
Die Anzeige erfolgt über einfache, übersichtliche Graphen.

- [ ] #122 
- [ ] #94

**Comment by CorentinHamp** [comment]
Statistiken werden aus zeitlichen Gründen nicht mehr implementiert
