### ISSUE TITLE
calenderView wird nicht vollständig

### ISSUE THREAD

**Issue by GrandpaNeubert** [HansenBerlin/altenheim-kalender#139]
![image](https://user-images.githubusercontent.com/82511692/120828718-2519a480-c55d-11eb-8ada-b27c8f12d5cd.png)

calenderView nicht vollständig sichtbar!
Weder
- [x] bei fullscreen 
- [x] dynamisches Fenster

**Comment by HansenBerlin** [comment]
sollte mit #140 gefixt sein, bitte mal testen
