### ISSUE TITLE
Lastenhefterstellung

### ISSUE THREAD

**Issue by HansenBerlin** [HansenBerlin/altenheim-kalender#15]
inhaltliche Erstellung des Lasten- und Pflichtenheftes (Layout egal)

	Lastenheft:

Definition: Die Anforderung an das Projekt wird unabhängig der Realisierung von Auftraggeber beschrieben.

1.	Zielbestimmung
-	Auftraggeber setzt die anfangs Anforderung fest
1.1	Musskriterien
-	Unablässige Kriterien, damit die Anwendung funktioniert 
1.2	Wunschkriterien
-	Entbehrliche Kriterien, kann erstellt werden, ist aber keine Pflicht
1.3	Abgrenzungskriterien
-	Kriterien, was klarstellt, was die Anwendung nicht beinhalten soll
2.	Produkteinsatz
-	Auftraggeber setzt die Zielgruppe fest
2.1	Anwendungsbereich
2.2	Zielgruppen
2.3	Betriebsbedingung
3.	Zustands Beschreibung
-	Notwendige Information für den Auftragnehmer
3.1	Ist-Zustand
-	Kurze Skizzierung der aktuellen Situation und Gegebenheiten
-	Auftraggeber hat die Möglichkeiten bestimmte Probleme und Missverständnisse zu schildern
3.2	Soll-Zustand
-	Auftraggeber beschreibt, welche Ziele auf dem Weg erreicht werden sollen
-	Wünsche
4.	Produktübersicht (?)
-	Über alle die Anwendung betreffenden Geschäftsprozesse und Akteure
5.	Projekteinführung
-	Die Zieldefinition, der gewünschte Ablauf, die Terminplanung sollen beschrieben werden
6.	Benutzeroberfläche
-	Setzt die grundlegende Anforderung fest, wie die Oberfläche aussehen soll
7.	Sonstige Anforderungen
-	Dokumentation und Sicherheitsanforderungen, wie z.B Passwortschutz
-	Der Auftraggeber gibt die Anforderungen vor
8.	Definition von Schnittstellen und Zuständigkeiten (?)
-	Erläuterung über die personelle Verteilung der Verantwortungsbereiche
-	An welchen Punkt treffen diese Zuständigkeiten aufeinander?
9.	Anforderung an die Projektdurchführung
-	Der Auftraggeber setzt wichtige Meilensteine fest
9.1	Zuverlässigkeit
9.2	Benutzbarkeit
10.	Ergänzung
-	Z.B. die Auflistung von Patente und Lizenzen
11.	Glossar

Pflichtenheft

Definition: Die konkrete Realisierung der Anforderungen wird beschrieben.

1.	Zielbestimmung
-	Dient als Vertragsgrundlage
-	Verbesserungen könne vorgeschlagen werden
-	Inhalt wie im Lastenheft + Verbesserungen
1.1	Musskriterien
1.2	Wunschkriterien
1.3	Abgrenzungskriterien
2.	Produkteinsatz
-	Auftragnehmer übernimmt die Vorgaben des Arbeitgebers
2.1	Anwendungsbereich
2.2	Zielgruppen
2.3	Betriebsbedingungen
3.	Produktumgebung
-	Auftragnehmer beschreibt detailliert den Einsatz des Produktes
3.1	Software
3.2	Hardware
3.3	Orgware (?)
4.	Produktfunktion
-	Erklärung jedes einzelnen Anwendungsfalls
-	Beschreibt unterstützende Funktion des Produkts
-	Wer ist beteiligt?
-	 Wie und unter welchen Bedingungen laufen die Funktionen ab?
-	Wie wirkt sich das auf die weiteren Geschäftsprozesse aus?
4.1	Anonymer Benutzer (?)
4.2	Autorisierter Benutzer (?)
4.3	Administrator (?)
5.	Produktleistung
-	Beschreibt Anforderungen an eine bestimmte Funktion
-	Z.B. Ausführungszeit, Genauigkeit der Berechnung Datentransfervolum und Dauer
-	Erfasst auch Anmerkungen an die Anforderungen, und ob diese überhaupt erreicht werden können
6.	Benutzeroberfläche
-	Grundlegende Anforderungen zur Art des Layouts, der Dialogstruktur und der Zugriffsrechte 
-	Erstellung eines Mockups
7.	Entwicklungsumgebung
-	Technisches Umfeld
-	Eine Auflistung der Soft- und Hardwaresysteme, die für die Anwendung zu installieren ist, sollte erstellt werden
-	Um die Verfügbarkeit des Netzwerkanschlusses garantieren, werden Rahmenbedingung festgelegt
-	Schnittstellen werden bekannt, um das Produkt mit anderen Anwendungen zu verknüpfen
7.1	Software
7.2	Hardware
7.3	Orgware (?)
8.	Qualitätsbestimmung
-	Bestimmten Merkmalen wird einer Qualitätsstufe zugeordnet
-	Z.B. Änderbarkeit = nicht relevant, Effizienz = gut, usw.
9.	Anforderungen an die Projektdurchführung
-	Die Anforderungen, Meilensteine des Auftraggebers werden übernommen
10.	Globale Testszenarien und Testfälle
-	Dient zur Absicherung
-	Prüfung des Produkts in Bezug auf Funktion, Eigenschaften und Qualitätsmerkmalen
-	Tests, die den größten Teil der Funktion abdecken, werden dokumentiert
-	Erstellung von Use Cases (?)
10.1	Systemkonfiguration (?)
10.2	Funktion des autorisierten Benutzers (?)
10.3	Funktion des anonymen Benutzers (?)
11.	Ergänzung
-	Übernahme der Informationen des Arbeitgebers
-	Dient ebenfalls zur Absicherung
12.	Glossar

Bemerkung:
Das sind Gliederungen für das Lasten- und Pflichtenheft + ein paar Definitionen.
Könnt ihr Bitte die Gliederungen kontrollieren. Fehlt da was, soll was entfernt werden, soll da was verändert werden? Stimmen die Definitionen?
Könntet ihr auch zu den Punkten auch ein Paar Informationen hinzufügen?
Ich würden den Text dann am Wochenende schreiben, würde das so klappen?
Danke im voraus :-)

**Comment by HansenBerlin** [comment]
@CorentinHamp  und @KamillaB-oss ladet ihr hier dann noch das aktualisierte LH hoch?

**Comment by CorentinHamp** [comment]
[Lastenheft entwurf.docx](https://github.com/HansenBerlin/altenheim-kalender/files/6596749/Lastenheft.entwurf.docx)

**Comment by CorentinHamp** [comment]
[Lastenheft entwurf.docx](https://github.com/HansenBerlin/altenheim-kalender/files/6596835/Lastenheft.entwurf.docx)

**Comment by HansenBerlin** [comment]
@CorentinHamp oder @KamillaB-oss könnt ihr das finale LH hier bitte noch hochladen?

**Comment by CorentinHamp** [comment]
[Lastenheft.docx](https://github.com/HansenBerlin/altenheim-kalender/files/6619467/Lastenheft.docx)
