### ISSUE TITLE
Datenpersistenz

### ISSUE THREAD

**Issue by HansenBerlin** [HansenBerlin/altenheim-kalender#158]
Die Kalenderdaten, Kontaktdaten und Settings müssen persistent gespeichert werden können. Fragen zu klären/Research:

- [x] Ist Java Serialisierung performant genug für unseren Usecase? Wir können mal von durchschnittlich 5 Terminen/Tag ausgehen, ums etwas zu skalieren sagen wir mal wir haben 5 Kalender. Also 25*1 Jahr ist roundabout 10k. Wir speichern 10 Jahre, also 100k Einträge. Damit hätten wir als Benchmark auf jeden Fall eine sehr konservative Schätzung. ;-) Kontakte und Settingseinstellungen sind dazu im Vergleich zu vernachlässigen. Da wir nicht jede Änderung aus der gespeicherten Datei laden, sondern nur initial, sollten wir testen wie lange es bei 100k Objekten auf einem Standardrechner dauert. Ebenso das Speichern wenn ein Termin eingetragen wird
- [x] wenn das zu langsam ist mal Objektdatenbanken checken? Relational ist ziemlich aufwendig (wenn auch sicherlich mit Abstand am performantesten), da wir dann mit unseren Datenformaten rumhantieren müssen (oder? Datenbank anyone?))
- [x] Entscheidung wann wird wo was gespeichert (direkt bei Erstellung, in Intervallen, manuell?)
- [x] Entscheidung Backup (grade bei Ser.) --> was ist wenn das letzte File corrupted ist, wir könnten dann das vorletzte laden. Also quasi immer ein Fallback?

Wenn das geklärt ist Implementierung. Das sollte von einem eigenen Controller, den die Objekte die laden/speichern müssen nutzen können (statt selbst IO Zugriffe zu machen).

**Comment by Stier-09** [comment]
Halte relationale Datenbanken für geeignet, da wir z.B. bei den Calender Entrys auch schon mit id´s arbeiten und somit die Objekte relativ einfach in Tabellen übertragen können. 
Für die lokale Speicherung würde ich MySql lite nehmen. 
Vom Aufwand her sollten die Klassen zur Übertragung der Objekte zur Datenbank und zurück in 2 Tagen realisierbar sein

**Comment by Stier-09** [comment]
Java Serialisierung wird wahrscheinlich zu unperfomant sein für unseren Anwendungsfall.
Neue Einträge würde ich direkt bei der Erstellung in der DB speichern.
Laden der Objekte wäre aus Sicht der Performance am besten, wenn dies nur Intervallweise passiert (z.B. Monats oder Jahrweise).

**Comment by HansenBerlin** [comment]
Ok, ich checke das mal probeweise mit der Serialisierung mit 50-100k Kalenderobjekten, sonst sollte ja, da wir nur mit Daten, Strings und ints arbeiten die Aufbereitung der Daten für die DB wirklich nicht so schwierig sein wie es klingt.
Was das Intervall angeht seh ich das etwas anders, wir müssen jedes Mal beim Programmstart die Daten laden und wenn Einträge/Settings geändert werden. Also eher oft - was ggfs ein weiteres Argument für eine DB ist.
