### ISSUE TITLE
Switch Light und Dark mode

### ISSUE THREAD

**Issue by HansenBerlin** [HansenBerlin/altenheim-kalender#160]
Als User möchte ich über einen einfachen Toggleswitch zwischen einer hellen und dunklen Ansicht wechseln können.

Akzeptanzkriterien:
Wechsel der Modes mit einem Klick
Speichern der letzten Einstellung und entsprechende Darstellung nach Programmneustart

- [x] CSS Files erstellen
- [x] CSS dynamisch laden
- [x] Events für Button zum wechseln
- [x] Speichern der letzten Einstellung

**Comment by HansenBerlin** [comment]
Buttons über Kalender noch blau unabhängig des Modus.

**Comment by nicoregenberg** [comment]
Dark Mode Hintergrund in Monatsansicht von aktuellem Tag und angeklickten Tag ist zu hell um Termine lesen zu können.

**Comment by nicoregenberg** [comment]
Kalenderansicht: 
blaue Buttons obere Leiste von Buttons (falsche farbe) + linie von aktueller Uhrzeit im DarkMode Rot, nicht Grau

kleiner Kalender rechts neben Tageszahl die Wochentage grün im darkmode (Kalenderliste ausgefahren)

![image](https://user-images.githubusercontent.com/82573216/128069661-0638d331-16b1-4bec-a876-8b440641fdf7.png)
