### ISSUE TITLE
Implementierung von I/O-Funktionalitäten

### ISSUE THREAD

**Issue by dannyneup** [HansenBerlin/altenheim-kalender#165]
relates to:
- [x] #23 
- [x] #24 
- [x] #25

**Comment by HansenBerlin** [comment]
Nicht abschließend getestet, erst dann sind Issues auch done.

**Comment by HansenBerlin** [comment]
bitte mit .27 mal durchtesten, also alle Fälle (Speichern, Laden, Files löschen, Ordner löschen etc.)

**Comment by dannyneup** [comment]
.28 failed:

- export einzelner Einträge nicht möglich
- export als Backup (inklusive Einstellungen) nicht möglich
- import funktioniert
- export von allen Kalendern funktioniert ebenfalls
