### ISSUE TITLE
Tooltips um Funktionen zu erklären

### ISSUE THREAD

**Issue by HansenBerlin** [HansenBerlin/altenheim-kalender#185]
Statt eines Handbuchs oder interaktiven Tutorials können wir Tooltips nutzen, die JFX defaultmäßig bietet. Beim ersten Starten kann der Nutzer ja ein bisschen an die Hand genommen werden (initialer Import...) und darauf hingewiesen werden, dass man die Tooltips deaktivieren kann (und wo).

**Comment by CorentinHamp** [comment]
Tool-Tip Option in den Einstellungen aändert nichts am Programm, wollten wir die nicht sogar rausnehmen?

Build: 0.4.28
