### ISSUE TITLE
Systemnachricht bei anstehenden Termin

### ISSUE THREAD

**Issue by Stier-09** [HansenBerlin/altenheim-kalender#192]
Das System soll eine Nachricht anzeigen, wenn eine bestimmte Zeit vor dem Termin erreicht ist und wenn der Termin beginnt.

relates to #258

**Comment by Stier-09** [comment]
nach Recherche festgestellt, dass es kein Event beim beginn eines Termins gibt, also muss in regelmäßigen Abständen (z.B. 1min) geprüft werden, ob demnächst ein Termin beginnt / ob gerade ein Termin beginnt)
Quelle für Recherche: https://dlsc.com/wp-content/html/calendarfx/manual.html#_distribution

**Comment by HansenBerlin** [comment]
![image](https://user-images.githubusercontent.com/42807459/127584651-db606795-d459-44e9-9fa3-dc451e22364e.png)

Icon nicht sichtbar und related zu #227 werden die Systray Prozesse auch nach Beenden nicht geschlossen.

**Comment by HansenBerlin** [comment]
bitte mit .27 retesten

**Comment by CorentinHamp** [comment]
Build 0.4.28: Erinnerungen funktionieren
