### ISSUE TITLE
Smart Serch skippt immer zwei Tage 

### ISSUE THREAD

**Issue by Stier-09** [HansenBerlin/altenheim-kalender#224]
man tippt auf nächster Tag und es geht zwei tage weiter
![image](https://user-images.githubusercontent.com/82510949/126836543-0056cce6-8e01-43f7-8342-511f2c195c63.png)
![image](https://user-images.githubusercontent.com/82510949/126836732-7aff1dd8-8bd2-4dae-98c9-420ace9d02ef.png)
![image](https://user-images.githubusercontent.com/82510949/126836860-180ff254-a49d-4fb4-9df7-ad89b0f8506d.png)

**Comment by HansenBerlin** [comment]
Bitte mit Build 19 retesten
