### ISSUE TITLE
Einstellung- die View ist verschoben

### ISSUE THREAD

**Issue by KamillaB-oss** [HansenBerlin/altenheim-kalender#225]
Nachdem ich die Jar-File geöffnet hatte, sah die Einstellung verschoben aus.
![verschobenEinstellungen](https://user-images.githubusercontent.com/83229084/126866707-c815b846-a192-49ca-b3d3-09b952642393.PNG)

relates to #257

**Comment by HansenBerlin** [comment]
Wird responsive angepasst und nicht einfach durch hardgecodete Fensterbreiten der Mainview. War bereits implementiert, muss noch angepasst werden. Not done....
