### ISSUE TITLE
Planner -leere Buttons

### ISSUE THREAD

**Issue by KamillaB-oss** [HansenBerlin/altenheim-kalender#226]
Nachdem ich die Jar-File geöffnet habe, sind leere Buttons zu sehen.
![leereFelder](https://user-images.githubusercontent.com/83229084/126866754-c31149fe-899a-4d32-bf54-1c9dd9ad2792.PNG)

**Comment by Stier-09** [comment]
Fix: add dependency for kordamp.ikonli lip

Code:
<dependency>
        <groupId>org.kordamp.ikonli</groupId>
        <artifactId>ikonli-javafx</artifactId>
        <version>12.2.0</version>
    </dependency>
