### ISSUE TITLE
Programm wird nicht beendet

### ISSUE THREAD

**Issue by Stier-09** [HansenBerlin/altenheim-kalender#227]
Programm wird zwar ausgeblendet aber nicht beendet (ist im Hintergrund noch aktiv)

**Comment by HansenBerlin** [comment]
Welcher Prozess läuft denn noch? Könnte eventuell die Notfication im Systray sein, bitte mal checken ob es auch auftritt wenn das deaktiviert ist um den Fehler einzugrenzen.

**Comment by HansenBerlin** [comment]
Die Prozesse der Benachrichtigungen im Systray laufen nach Beenden manchmal weiter. Kann es nicht zuverlässig reproduzieren, muss aber noch gecheckt werden.

**Comment by Stier-09** [comment]
Habs getestet, liegt nicht am Tray, selbst wenn er nicht gestartet wird, dann wird das Programm nicht beendet

**Comment by CorentinHamp** [comment]
Fix in 0.4.28
