### ISSUE TITLE
Termindauer wurde nicht beachtet

### ISSUE THREAD

**Issue by KamillaB-oss** [HansenBerlin/altenheim-kalender#228]
Nachdem ich die Jar Datei gestartet habe, habe ich die smart Search ausgewählt und die Termindauer auf vier Stunden gestellt. Sonst habe ich keine weiteren Informationen angegeben. Der vorgeschlagene Termin dauert nur 15 min.
![Termindauer](https://user-images.githubusercontent.com/83229084/126878932-a11cf1be-b071-4a0c-b6dc-fd4e9182ac0f.PNG)
Build  0.3.14

**Comment by HansenBerlin** [comment]
Retest mit Build 19
