### ISSUE TITLE
Hin- und herspringen des UI beim Verkleinern des Fensters

### ISSUE THREAD

**Issue by CorentinHamp** [HansenBerlin/altenheim-kalender#230]
Beim horizontalen Verkleinern des Fensters verändert sich die UI folgendermaßen:
- Verkleinern aller Bereiche ausgenommen des Reiters auf der linken Seite (wie geplant)
- verschwinden des Tagesanzeige+ Monatsübersicht-Fensters
- verkleinern der Restlichen Elemente, ausgenommen des Reiters auf der linken Seite
- wierderauftauchen des mittleren Fensters, verkleinern der Reiter auf der Linken Seite
- verkleinern der restlichen Elemente
- verschwinden des Mittleren Fensters

Soweit ich es aus den Meetings entnehmen konnte, war es geplant, dass sich erst der linke Reiter verkleinert und danach ggf. das Mittelfenster verschwindet. das weggehen und wiederauftauchen des Mittelfensters ist außerdem sehr verwirrend für den Nutzer

Build: 0.3.16

relates to #257

**Comment by CorentinHamp** [comment]
[2021-07-25 21-45-39.zip](https://github.com/HansenBerlin/altenheim-kalender/files/6874465/2021-07-25.21-45-39.zip)
hier eine Videoaufnahme davon

**Comment by HansenBerlin** [comment]
In welcher View tritt das auf, nur Planner oder auch die anderen?
