### ISSUE TITLE
verkleinerung der UI bei unterschiedlichen Bildschirmauflösungen

### ISSUE THREAD

**Issue by CorentinHamp** [HansenBerlin/altenheim-kalender#231]
mein Zweitbildschirm hat eine geringere Auflösung als mein Erstbildschirm, wenn ich also die Anwendung zuerst in meinem Erstbildschirm, dann in meinem Zweitbildschirm und dann wieder in meinem Erstbildschirm  auf Vollbild schalte, ist die gesamte UI stark verkleinert.
![image](https://user-images.githubusercontent.com/82573527/126911408-0dcb4b46-a411-492a-a6c6-3a55f6dd50f1.png)

**Comment by Stier-09** [comment]
ist ein Java / Windows Problem können wir nicht so leicht fixen
