### ISSUE TITLE
Smart-Search-Fehler! Datum wird nicht erkannt

### ISSUE THREAD

**Issue by CorentinHamp** [HansenBerlin/altenheim-kalender#235]
Bei einer Datumsangabe ohne Jahreszahl (Bsp. einfach 05.08.) erkennt die Smartsearch das Datum nicht richtig und sucht deswegen trotz manueller Zeitspannenauswahl nach dem nächstmöglichen Termin. Video im Zip-Format ist beigefügt

Build: 0.3.18

(P.s. könnte sich das nicht theoretisch durch eine Default-Jahreszeitenangabe lösen lassen? Nach dem Motto: wenn keine Jahreszahl vorhanden, setze Jahreszahl auf aktuelles Jahr. Ist nur ne fixe Idee)
[2021-07-26 21-18-18.zip](https://github.com/HansenBerlin/altenheim-kalender/files/6880652/2021-07-26.21-18-18.zip)

**Comment by HansenBerlin** [comment]
bitte mit build 19 testen, es sind jetzt qua Konvention keine manuellen Eingaben möglich, das Datum wird aussschließlich über den Datepicker gewählt (und damit korrekt validiert)

**Comment by CorentinHamp** [comment]
Fehler tritt nicht mehr auf, da (wie du schon erwähnt hast) keine manuellen Eingaben mehr möglich sind
