### ISSUE TITLE
Änderungen am Kalender werden nach dem schließen und wieder öffnen nicht mehr angezeigt

### ISSUE THREAD

**Issue by CorentinHamp** [HansenBerlin/altenheim-kalender#239]
Ich habe über die Smart-Search Funktion einen Termin zum Kalender hinzugefügt, nachdem ich die Anwendung dann allerdings geschlossen und wieder geöffnet habe, war der Termin weg. Auch Veränderungen an den Dummy-Terminen wurden nicht gespeichert. (Video kann ich gerade nicht hinzufügen, sollte aber auch so reproduzierbar sein, falls nicht, gerne noch einmal durchschreiben)

Build: 0.3.19

**Comment by HansenBerlin** [comment]
Habs grad gecheckt, es werden gar keine Termine gespeichert auch nicht durch die ganz normale Funktion hinzugefügte. Da wurde beim Wiedereinbau der IO Funktion irgendwo was vergessen/verändert, also da mal gucken. Also Scope hier auf IO und Smartsearch weiter testen, relevanter Fokus ist ob die Termine richtig eingetragen werden (derzeit im ersten Kalender nach dem Standard Kalender).
In der IO Funktionalität muss sichergestellt sein, dass jedes Mal wenn ein Kalendereintrag erstellt wird, der auf dieses Event registrierte Listener mit dem IO Controller persisitiert. Dieses Event gibt es auf jeden Fall in CalFX. Es ist nicht Aufgabe der einzelnen Views das zu tun.

**Comment by HansenBerlin** [comment]
Nachtrag: Es gibt einen Fehler mit den HWR Kalendern, da werden viel zu viele redundant in den Kalenderarray geladen und entsprechend kommt es zu Konflikten. Wenn der gespeicherte HWR Kalender gelöscht wird wird alles wie geplant in den generierten Kalender eingetragen. Also klar IO Scope, hier bitte nochmal gewissenhaft alles checken beim Laden und speichern der Kalender.

**Comment by HansenBerlin** [comment]
Ich mach das, bei dem Einbau der IO Sachen ist noch einiges unbeachtet. betrifft auch #242

**Comment by CorentinHamp** [comment]
Verschlimmerung des Problems in Build 0.3.21: nicht einmal mehr die Ursprungsform der Dummy-Kalender wird abgespeichert

**Comment by CorentinHamp** [comment]
Issue gefixed in 0.4.28 (Bedingung: am Kalender wurde vor dem schließen was geändert)
