### ISSUE TITLE
Website Scraper Aktualisierung

### ISSUE THREAD

**Issue by HansenBerlin** [HansenBerlin/altenheim-kalender#242]
Nur wenn der Kalender vom aktuell gespeicherten abweicht soll gespeichert werden. Alternativ immer löschen des aktuellen HWR Kalenders und Überschreiben, egal ob Änderungen da sind. Derzeit wird jedesmal ein neuer Kalender gespeichert (intern, sieht man in der View nicht).
Blocker für #239

**Comment by nicoregenberg** [comment]
Funktioniert Grundlegend.
Kleines Problemchen beim erneuten abspeichern:
Beim wechseln/aktualisieren des Kalenders in den Einstellungen muss man 2x Speichern klicken. 
Beim 1. Speichern-klick wird der alte Kalender gelöscht, beim 2. Speichern-klick wird der neue Kalender gespeichert. Muss man auf jedenfall drauf kommen bzw. vllt die Meldung nach dem 1. Speichern "alter Kalender wurde gelöscht, nochmal speichern zum Hinzufügen des neuen / der neuen version"
