### ISSUE TITLE
überfällige Termine werden vorgeschlagen

### ISSUE THREAD

**Issue by KamillaB-oss** [HansenBerlin/altenheim-kalender#243]
In der Smart Search werden ungültige Termine vorgeschlagen.
Voreinstellung: Terminnamen eingegeben und Termindauer auf 34 min gesetzt.
Abfrage habe ich am 27.07.2021 um 16:40 gestellt.
Build: 0.3.19
![verspaetet](https://user-images.githubusercontent.com/83229084/127174981-e8ee6b77-997b-4a59-a830-93cb64fd3b87.PNG)

**Comment by HansenBerlin** [comment]
bitte mit .27 retesten

**Comment by CorentinHamp** [comment]
![image](https://user-images.githubusercontent.com/82573527/128436164-c1d38f27-3b89-4113-920f-7718525ae7c1.png)
Isuue besteht noch in Build 0.4.28
