### ISSUE TITLE
Zeitvorgabe bei Smarttermin 9 Stellen nach dem Komma

### ISSUE THREAD

**Issue by CorentinHamp** [HansenBerlin/altenheim-kalender#255]
- [x] Helferklasse zur Umrechnung
- [x] Implementierung an allen Stellen an denen Daten in der View angezeigt werden (Vorschlagsliste Smartsearch, Popup bei Kalendereintrag nach Smartsearch, Mailtemplate) 

Bei einem Smartsearchtermin wurde mir gerade ein auf die Nanosekunde genauer Termin vorgeschlagen. Keine Ahnung, ob es reproduzierbar ist, ist bisher bei mir auch nur mit diesen Einstellungen aufgetreten. 1 Dummy- Kalender ist drin, an dem Tag sind aber keine Termine. 
![Einstellungen](https://user-images.githubusercontent.com/82573527/127454605-42921c29-4a34-4d25-a5a8-d769f26e699c.jpg)
![aufdieNanosekunde](https://user-images.githubusercontent.com/82573527/127454624-936907b3-35c5-49b8-af22-9e3a43795b38.jpg)

Build: 0.3.23

**Comment by HansenBerlin** [comment]
bitte mit .27 retesten
