### ISSUE TITLE
Kalender Hinzufügen trotz Abbrechen wird ein Kalender hinzugefügt

### ISSUE THREAD

**Issue by Stier-09** [HansenBerlin/altenheim-kalender#256]
Wenn man neben Kalender auf das "+" drück öffnet sich das Dialogfeld zum hinzufügen eines neuen Kalenders, wenn man dort auf Abbrechen drückt oder das Fenster schließt wird trotzdem ein Kalender mit dem Namen "Neuer Kalender hinzugefügt" bzw. dem Namen den man eingegeben hat hinzugefügt zur View, jedoch werden diese Kalender nicht gespeichert.
![image](https://user-images.githubusercontent.com/82510949/127662076-06ea80b4-f64c-4a31-a71f-65ce10f237db.png)
Build: 0.3.24

**Comment by HansenBerlin** [comment]
retest mit aktuellem Build

**Comment by CorentinHamp** [comment]
Build 0.4.25: Problem tritt nicht mehr auf
