### ISSUE TITLE
Minimale Fenstergröße existiert nicht mehr

### ISSUE THREAD

**Issue by Stier-09** [HansenBerlin/altenheim-kalender#257]
Es muss wieder eine minimale Fenstergröße festgelegt werden, da sich sonst die UI komisch verschiebt / es zu Fehler bei der Anzeige der UI kommt.
Build: 0.3.24

Beispiele:
![image](https://user-images.githubusercontent.com/82510949/127663135-b3637008-3899-4fa0-933a-a58f35d2f3c0.png)
![image](https://user-images.githubusercontent.com/82510949/127663210-ac3a5228-5ef6-476d-a595-f9ed1181a13e.png)
![image](https://user-images.githubusercontent.com/82510949/127663246-020bc17c-4777-4755-8610-34a5da7389a9.png)
klein und wieder groß bei geöffneter Ansicht der Kalender
![image](https://user-images.githubusercontent.com/82510949/127663458-5ebe6c3c-b944-4f8e-aef4-776480386151.png)

**Comment by HansenBerlin** [comment]
Nein, wir haben doch drüber gesprochen! Ich habe eine Methode in der ich das mache, aber lass dieses Gepatche bitte. Und die doppelt und dreifache Arbeit. Es nervt langsam.

**Comment by HansenBerlin** [comment]
Und nebenbei: ein Bugticket enthält die Fehlerbeschreibung und nicht den (vermeintlichen) Lösungsweg.
