### ISSUE TITLE
Erinnerung erscheint zweimal

### ISSUE THREAD

**Issue by HansenBerlin** [HansenBerlin/altenheim-kalender#258]
Wenn der Termin ansteht kommt eine Erinnerung für "jetzt" und anschließend sofort noch eine für "in 0 Minuten". 
-Termin in den nächsten 5 mn beginnend erstellen und das Programm laufen lassen
-auf den Systray achten
-Build 3.24

**Comment by CorentinHamp** [comment]
nicht reproduzierbar
