### ISSUE TITLE
Fahrtzeiten werden in der Smartsearch nicht berücksichtigt

### ISSUE THREAD

**Issue by CorentinHamp** [HansenBerlin/altenheim-kalender#261]
Trotz aktivierter Fahrtzeit inkl. Verkehrsmittelauswahl wird der Zeitaufwand für die Fahrtzeit bei den terminvorschlägen nicht berücksichtigt. Genaue Einstellungen im Video.

Build: 0.3.24
[2021-08-02 16-43-33.zip](https://github.com/HansenBerlin/altenheim-kalender/files/6917741/2021-08-02.16-43-33.zip)

**Comment by nicoregenberg** [comment]
auch in 0.4.25 nicht.

**Comment by CorentinHamp** [comment]
Weiterer Teil des Problems: wenn automatische Eintragung bei den gezeigten Einstellungen aktiviert ist, reagiert der "weiter"Button auf Seite 2 nicht.

Build: 0.4.25

**Comment by HansenBerlin** [comment]
Das ist korrekt so. Die An und Abfahrt sollen ja nicht als Termine angezeigt werden in der Übersicht, sondern nur die Termine selbst. Wenn dann ein Termin eingetragen wird (automatisch oder manuell) werden diese Termine als zusätzliche Termine vorher  und hinterher eingetragen. Hintergrund: Ich kann diese dann löschen wenn ich doch nicht fahre und der eigentliche Termin bleibt erhalten. Zudem wäre ein zweistündiger Termin sonst viel länger bei langer An- und Abfahrt, was natürlich im Kalender keinen Sinn macht. Beispiel: Termin 1 Stunde, Anfahrt berechnet mit 1 Stunde an und ab. Es werden drei einstündige Termine hintereinander eingetragen, An und Abfahrtstermine heißen auch anders. Die Lücken zwischen den Terminen sind die Fahrtzeiten, damit man nicht mehrere Termine eintrage kann und sich die Zeiten überschneiden - das könnte man ggfs. überdenken.
Was den Button angeht: da hängt das Programm weil die Anfrage nicht funktioniert (ist meine These). Bitte mal checken, da es bei mir mit auto on/off nicht nachstellbar ist.

**Comment by nicoregenberg** [comment]
weiterführende Tests:
Der Fehler gilt nur für Freie Zeit "Vor" dem Termin (ebenso wie für die Fahrzeit). Diese wird nicht berücksichtigt. 
Die (Fahr)Zeit "Nach" dem Termin wird berücksichtigt.

**Comment by CorentinHamp** [comment]
Fahrtzeit inkl. seperater Termineintragung funktioniert für mich in Build 0.4.25, allerdings mit dem in #270 beschriebenen Problem

**Comment by HansenBerlin** [comment]
bitte mit .27 retesten

**Comment by HansenBerlin** [comment]
retest mit .28

**Comment by CorentinHamp** [comment]
Issue gefixt in 0.4.28
