### ISSUE TITLE
Terminerstellung: Wiederholung (alle einstellungen)

### ISSUE THREAD

**Issue by nicoregenberg** [HansenBerlin/altenheim-kalender#262]
Kalender geöffnet
Termin mit doppelklick erstellt
Namen gegeben / Zeit geändert (ist egal)
Intervall eingestellt (zb "Jeden Tag")
nächsten Tag angeschaut - kein Termin vorhanden
zurück auf aktuellen Tag (des Termins) gegangen 
angelegter Termin ist verschwunden

build 0.4.25

https://user-images.githubusercontent.com/82573216/127894362-637fa5c3-d830-4da1-a72c-1d95bbcdf263.mp4

**Comment by HansenBerlin** [comment]
Das ist ne tote Funktion von CalFX, müssen wir entweder implementieren oder den Button rausschmeissen. Hat aber nichts mit unserem Code zu tun.

**Comment by HansenBerlin** [comment]
wird mit #263  gefixt
