### ISSUE TITLE
aktuelle zeit in Kalender View läuft nicht weiter

### ISSUE THREAD

**Issue by Stier-09** [HansenBerlin/altenheim-kalender#265]
![image](https://user-images.githubusercontent.com/82510949/128061545-97b86f85-f796-4317-92dc-899164814cf8.png)
keine Änderungen nur gestartet
Build: 0.4.25

**Comment by HansenBerlin** [comment]
bitte mit .27 retesten

**Comment by CorentinHamp** [comment]
Issue gefixed in 0.4.28
