### ISSUE TITLE
Terminvorschläge automatisierte Erinnerungen

### ISSUE THREAD

**Issue by nicoregenberg** [HansenBerlin/altenheim-kalender#27]
Als User wünsche ich mir die Funktion Terminvorschläge, die regelmäßig bzw. wiederholt vorgeschlagen werden, entweder bis ich sie ausschalte oder eine maximale Anzahl von Vorschlägen des einen Termins erreicht ist.

Akzeptanzkriterium:
Der User kann Terminvorschläge "schlummern" lassen oder verschieben, auf einen Zeitpunkt, wenn er Zeit hat. Wenn der Kalender gepflegt ist, sollte der User dann erinnert werden, wenn kein Eintrag im Kalender vorgesehen ist (der User also "Zeit" hat).

- [x] #122 
- [x] #125 
- [x] #99 
- [x] #94

**Comment by HansenBerlin** [comment]
Wird aus Zeitgründen und weil es keine zwingende Anforderung war nicht umgesetzt.
