### ISSUE TITLE
Smartsearch berücksichtigt Kalender nicht.

### ISSUE THREAD

**Issue by CorentinHamp** [HansenBerlin/altenheim-kalender#270]
Egal, ob bei der Kalenderberücksichtigung standard oder manuell ausgewählt ist, egal ob manuelle oder automatische Eingetragung aktiviert ist: Die Smartsearch berücksichtigt keinerlei Kalender bei der Suche. Einzige Ausnahme: andere Smartsearch-Termine werden berücksichtigt.

[Smartsearch.zip](https://github.com/HansenBerlin/altenheim-kalender/files/6931109/Smartsearch.zip)
Build: 0.4.25

**Comment by HansenBerlin** [comment]
retest mit .28

**Comment by CorentinHamp** [comment]
Issue gefixed
