### ISSUE TITLE
Adressen gelöschter Kontakte in der Smartsearch weiterhin auswählbar

### ISSUE THREAD

**Issue by CorentinHamp** [HansenBerlin/altenheim-kalender#271]
Titel sagt eigentlich alles. Build: 0.4.25
[Adressen.zip](https://github.com/HansenBerlin/altenheim-kalender/files/6931198/Adressen.zip)

**Comment by CorentinHamp** [comment]
Außerdem: bei Leereinträgen gibt es leere Auswahlmöglichkeiten

**Comment by HansenBerlin** [comment]
bitte mit .27 retesten

**Comment by HansenBerlin** [comment]
retest mit .28

**Comment by CorentinHamp** [comment]
Issue gefixed
