### ISSUE TITLE
Termin vereinbaren per Tel.

### ISSUE THREAD

**Issue by Stier-09** [HansenBerlin/altenheim-kalender#28]
## User Story
Als betagte Person möchte ich, dass der Kalender bei einem Terminvorschlag mir die Telefonnummer der dementsprechenden Einrichtung anzeigt, um dort einen Termin zu vereinbaren.

### Tasks
1. Speicherung der Telefonnummer (eventuell mehrere) der Einrichtung   
2. Anzeige der Telefonnummer beim Terminvorschlag  
3. Änderung der Telefonnummer der Einrichtung

## Akzeptanzkriterien
- Telefonnummer ist ein Teil der Maske des Terminvorschlags
- Telefonnummer ist ein Teil der Maske zum Anlegen von neuen Einrichtungen und werden auch darunter gespeichert
- Telefonnummer kann in der Maske einer bestehenden Einrichtung geändert werden

- [ ] #122 
- [ ] #125 
- [ ] #94

**Comment by HansenBerlin** [comment]
Da nicht für mobile umgesetzt wird invalid.
