### ISSUE TITLE
HWR-Import funktioniert nicht

### ISSUE THREAD

**Issue by CorentinHamp** [HansenBerlin/altenheim-kalender#283]
Titel sagt's eigentlich. Build 0.4.28, getestet mit WI 2. Sem. C, 3. Sem. C
[HWR-Import funktioniert nicht.zip](https://github.com/HansenBerlin/altenheim-kalender/files/6943622/HWR-Import.funktioniert.nicht.zip)

**Comment by Stier-09** [comment]
Importierter Kalender wird nicht gespeichert

**Comment by Stier-09** [comment]
Fehler Handling Scraper 
Check Import ics ist leer

**Comment by nicoregenberg** [comment]
funktioniert soweit.
Beim wechseln/aktualisieren des Kalenders in den Einstellungen muss man 2x Speichern klicken. 
Beim 1. Speichern-klick wird der alte Kalender gelöscht, beim 2. Speichern-klick wird der neue Kalender gespeichert. Muss man auf jedenfall drauf kommen bzw. vllt die Meldung nach dem 1. Speichern "alter Kalender wurde gelöscht, nochmal speichern zum Hinzufügen des neuen / der neuen version"

**Comment by HansenBerlin** [comment]
Sollte nach dem Refactoring gestern gefixt sein, plus kleiner Fix heute.
