### ISSUE TITLE
Terminvorschläge nach Öffnungszeiten u. Aufenthaltsort

### ISSUE THREAD

**Issue by Stier-09** [HansenBerlin/altenheim-kalender#29]
## User Story
Als Student möchte ich, dass mir der Kalender nur Tage und Uhrzeiten vorschlägt, an denen die Einrichtung offen hat.

### Tasks
1. Speicherung der Öffnungszeiten und Adresse der Einrichtung
2. Vorschläge von Terminen nur innerhalb der Öffnungszeiten
3. Auswahlmöglichkeit für einen Zeitraum, in dem ein Termin vorgeschlagen werden soll

## Akzeptanzkriterien
- Öffnungszeiten und Adresse sind ein Teil der Maske zum Anlegen von neuen Einrichtungen und werden auch darunter gespeichert (es sind Pflichtfelder)
- Öffnungszeiten und Adresse können in der Maske einer bestehenden Einrichtung geändert werden (Pflichtfelder)
- Öffnungszeiten und Adresse sind ein Teil der Maske des Terminvorschlags
- Termin werden für die jeweilige Einrichtung nur innerhalb der Öffnungszeiten vorgeschlagen
- In der Maske des Terminvorschlags kann der User einstellen in welchem Zeitraum ein Termin vorgeschlagen werden soll (mehrere Tage)

- [x] #122 
- [x] #125
- [x] #94

**Comment by HansenBerlin** [comment]
nicht abschließend getestet

**Comment by CorentinHamp** [comment]
[Öffnungszeiten.zip](https://github.com/HansenBerlin/altenheim-kalender/files/6944097/Offnungszeiten.zip)
funktioniert nicht, Build: 0.4.28. Weiter-Button reagiert nicht
