### ISSUE TITLE
Termin vereinbaren - Änderung der Vorlage

### ISSUE THREAD

**Issue by KamillaB-oss** [HansenBerlin/altenheim-kalender#33]
User Story:
Als vergesslicher Benutzer möchte ich den Inhalt der Vorlage der automatischen E-Mail ändern können, damit ich Informationen löschen oder auch hinzufügen kann.

Akzeptanzkriterien:
-es sollte bereits eine Vorlage existieren
-in den Einstellungen sollte eine Funktion vorhanden sein, die diese Änderungen durchführt oder 
(-es sollte bei der Auswahl zwischen automatischer E-Mail und selbstgeschriebender E-Mail, die Option "Vorlage ändern" vorhanden sein)

- [x] #122 
- [x] #125 
- [x] #94
- [x] #126

**Comment by CorentinHamp** [comment]
Alle benötigten Features in 0.4.28 vorhanden
