### ISSUE TITLE
Userstory_Importfunktion mit ICS Standard

### ISSUE THREAD

**Issue by GrandpaNeubert** [HansenBerlin/altenheim-kalender#37]
Als Nutzer soll der Import mithilfe des ICS Standards möglich sein.

Task:
1. Import bei erstmaliger Nutzung der Software anbieten
2. Import auch manuell später ermöglichen.
3. Importierte Termine den Standards anpassen können. (Benachrichtigungszeit vor dem Termin, Terminfarben, Freigaben)

Done if
Termine Fehlerfrei importiert werden
Termine automatisch den Standards angepasst werden
Termine manuell angepasst werden können (mehrere auf einmal) 

- [x] #122 
- [x] #103 
- [x] #94 
- [x] Testen: Können Kalender z.B. von Google mit anderen Properties als nur Datum, Zeit und Titel, bei uns importiert werden ohne Fehler entstehen (worst case) oder Daten verloren gehen (nicht ganz so schlimm aber muss man dann dem Nutzer sagen)

**Comment by HansenBerlin** [comment]
Terminfarben in den Settings aber nicht implementiert.

**Comment by CorentinHamp** [comment]
ICS-Import fehlerfrei möglich (Build: 0.4.28)
