### ISSUE TITLE
Userstory_Datenabgleich durch Freigabe auf andere vorhandene Kalender (Google, Apple, Microsoft)

### ISSUE THREAD

**Issue by GrandpaNeubert** [HansenBerlin/altenheim-kalender#38]
Kalenderimport soll durch die Freigabe auf Userkonten möglich sein (Google, Apple, Microsoft, opensource)

Task
1. Bei der Erstnutzung soll nach den Freigaben gefragt werden.

Done IF

Freigaben erteilt wurden und sich Termine selbstständig aktualisieren
Freigaben entzogen werden können
Aktualisierungshäufigkeit eingestellt werden kann
- [ ] #122 
- [x] #103 
- [ ] #94

**Comment by HansenBerlin** [comment]
Wird aus Zeitgründen und weil es keine zwingende Anforderung war nicht umgesetzt, also ohne Authentifizierung. Der Import anderer Kalender oder umgekehrt Export und dortiger Import funktioniert aber wie erfordert.
