### ISSUE TITLE
Userstory_scraping bestimmter vorher definierter Terminpläne von anderen Internetseiten (HWR Stundenplan)

### ISSUE THREAD

**Issue by GrandpaNeubert** [HansenBerlin/altenheim-kalender#39]
Über Kalenderänderungen vorher registrierter öffentlich einsehbarer Kalender informieren, sobald Abweichungen erkannt wurden.

Task
1. vorher registrierte Kalender regelmäßig aufrufen und mit bestehendem Kalender vergleichen
2. Bei Abweichungen User informieren (welcher registrierter Kalender sich geändert hat, ob die Änderung Übernommen werden soll)
3. Häufigkeit der Aktualisierungsanfrage einstellen

Done if
1. Gewünschte Kalender registriert werden können
2. Aktualisierungsrate einstellbar ist
3. Benachrichtigung über E-Mail/ App über Terminänderung

- [x] #122 
- [x] #103 
- [x] #102
- [x] #94

**Comment by HansenBerlin** [comment]
Wenn keine Internetverbindung besteht Fehler, also noch nicht fertig.

**Comment by Stier-09** [comment]
Funktioniert auch ohne Internet mit der Fehlermeldung "Network is unreachable: connect"
